#

In [1]:
!which python

/Users/karthikmaddukuri/anaconda3/envs/iris/bin/python


In [2]:
%load_ext autoreload
%autoreload 2

In [6]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import os
from sklearn import datasets
import seaborn as sns
%matplotlib inline

In [5]:
sns.set()

# Load Data

In [7]:
data = datasets.load_iris()

In [10]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [22]:
print(data['data'][:5], end='\n\n')
print(data['feature_names'])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


#### _The goal is to predict the species of the flower or classify the species into setosa, versicolor, or virginica._
**This is a  Multiclass classification problem**